name: market news data cron run
on:
    schedule:
        - cron: '53 22 * * *'
    workflow_dispatch:

jobs:
    build:
        name: Trigger cron action
        runs-on: ubuntu-latest
        steps:
            - name: cURL request
              run: curl -X GET ${{secrets.VERCEL_DOMAIN_FOR_CRON}}/getMarketNews
