name: quarterly data cron run
on:
    schedule:
        - cron: '20 23 1 * *'
    workflow_dispatch:

jobs:
    build:
        name: Trigger cron action
        runs-on: ubuntu-latest
        steps:
            - name: cURL request
              run: curl -X GET ${{secrets.VERCEL_DOMAIN_FOR_CRON}}/getQuarterlyStockData
